apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-typst-settings
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: text
          name: typstSelector
          label: typst-CSS选择器
          value: "typst[data-type=typst]"
          help: 用于匹配typst的CSS选择器
        - $formkit: text
          name: typstFontUrl
          label: typst-字体文件地址
          value: ""
          help: 用于渲染typst中的中日韩等文字
